[firebase]
type = "service_account"
project_id = "crm-hygge"
private_key_id = "7c6932319d84460494f7703ef0554a517e76fe1a"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD14fNful2qHW9Y
TZWzBALJUdNmPF2ZXCAp7tAPS3JGUpZPDDN+8nUq7QE0ZAxUjWF9/rMtaC04Acr7
FVbtJUPNGxHKSmJQ0wr5W8pAOzH/WjHYf66qNW7al3elU+X/tfQahABXNRbR765+
7yjAzZkjp1ve1jg4VfMPAMI+paUnFA0bxGtir82TpMCtUfSfl5z9nBbCH2dvUr1X
y1valxCubIebrcSWp4YLBzLU6pvPhLF3Q5qGjNwB20LabQn4lFE7Iqt88ZXwoOCz
5smnlA4Yit2Q+Bmb6lG8BbWMSzfNxHHZzRnzJcjVsBp8Hc/n20bPi7lrOtvYyZZL
A4qpypztAgMBAAECggEAKL/X2vlSrQ8ARUDkapzjTlSIhbTC6Vfmf7STmDlPeL6W
qQaTYTpS9zh8nt9m2LtumRg1PzT464OGjYqZk6c9n5gZIG6n8Q+szasr722wCUr8
IE521sAQvVrlagmnwDN6P0u5l7pVbBj+EQzXMu7P7qP9moZjnliGNeoRBxtiLcG2
ij2rd4VTyfYjrLEilKCpYYqBEoRI9wbHYgEtNLUNT9idwyGXKmRItTJPTKc+QbCv
YijhqY5yZHFlrcX/9b/Broo7tHTOR5sN1tWu5Vk/BcU8Ya3LL8XM0NsOVBpktuCb
RuvkW4KdE2sHiJy5ghCHeWQkG9aW1uSRwDg8Jk5GUQKBgQD8KHYEsa42ek3CTI1K
7Pct5sGoyj/VWxgE4x+62KtR+tPOXGdm8GoMaIUf9BbYXdBfYVlE513YOg5WsHYW
KlOZCM5RE81BoZxd3MR7wjndaiHZHJ62SXRhMJAer2fci5aHmQ+q5tODm2RSr0ZM
FG1AAdx1pt/W9pjZ1EHXkVYV8QKBgQD5oQMvLHKDSZbghMyrlsXi8ulhz7+rRJ5p
gFGKEJfRRvJB+hsvNgA22v/I23/Wrcqpzh1kLwRmv2ufX+gG68Zqj8xoQO5iPZpw
/RrTv9ZWKEFbdBd3PLq9C+U8d9CIwo1Gl/4D1hTeU3vn3SVvRBl8YOf97HGJOs3W
vlnXYXEKvQKBgAtqbYVi4ec3fEO6oX7t4Xbjhor0tRUcraay/aHA42ivuV0TU98W
LUboiHZc35fmD2PyDU+QRfBfGH0WOhJg0i4Qdv62rck13tVlBEQyE9qRTnz8zbak
9q7buvqYqFQUwbjb1hi/oH3J0C3qH32cQyHts6Rj7KhXu63I7T4sJ0CRAoGBAPfe
hF3sIYzxnmo0E1LydG4ky86+zdBPY4jYzJ5uWYGJk/YlVabsVQwjK0cThX3ytcEk
lBSthw5LVp87SRbOOQgI32xJxSsxhlBZUrEd1MNaV4Nq4/4XBEnBLQ983Ule/Y8y
Tx0aD0Cv3uHdulUgZroVM2b0x8v+4vMvsd/mtqt1AoGAcYMHO5PFTaiLE6jnKbjr
Hme9legdUGc1XzMurlsndllI0ClbnDKkl8WE6M/ypQn8B31RVTWK4biwLmUFqRsb
uDNRei8n4UuKHad6XhrCooH2zcI2IMD5th/Eh0G0mzzUqm1ctUh1mhSDhkNUqnZ1
7xTHZFz+snS5uKlItA+wyaw=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-idxya@crm-hygge.iam.gserviceaccount.com"
client_id = "101533254845328435375"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-idxya%40crm-hygge.iam.gserviceaccount.com"
universe_domain = "googleapis.com"