[auth]
redirect_uri = "https://crmhygge-vgrl2bpzo2dguqmv2xy23s.streamlit.app/oauth2callback"
cookie_secret = "fc7c9484abc4f4933b0022be0bfc5da4"

[auth.microsoft]
client_id = "2416c40e-33c3-4632-9f43-1884815ceeb8"
client_secret = "4Lz8Q~0aKVTfTfcWu0h1UWG1FmbiZt-uzGKMlbzL"
server_metadata_url = "https://login.microsoftonline.com/68c8d20f-fecd-4b5c-bf1b-8def71adada1/v2.0/.well-known/openid-configuration"
