[firebase2]
my_project_settings = { 
    type = "service_account", 
    project_id = "crm-hygge", 
    private_key_id = "7c6932319d84460494f7703ef0554a517e76fe1a", 
    private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD14fNful2qHW9Y\nTZWzBALJUdNmPF2ZXCAp7tAPS3JGUpZPDDN+8nUq7QE0ZAxUjWF9/rMtaC04Acr7\nFVbtJUPNGxHKSmJQ0wr5W8pAOzH/WjHYf66qNW7al3elU+X/tfQahABXNRbR765+\n7yjAzZkjp1ve1jg4VfMPAMI+paUnFA0bxGtir82TpMCtUfSfl5z9nBbCH2dvUr1X\ny1valxCubIebrcSWp4YLBzLU6pvPhLF3Q5qGjNwB20LabQn4lFE7Iqt88ZXwoOCz\n5smnlA4Yit2Q+Bmb6lG8BbWMSzfNxHHZzRnzJcjVsBp8Hc/n20bPi7lrOtvYyZZL\nA4qpypztAgMBAAECggEAKL/X2vlSrQ8ARUDkapzjTlSIhbTC6Vfmf7STmDlPeL6W\nqQaTYTpS9zh8nt9m2LtumRg1PzT464OGjYqZk6c9n5gZIG6n8Q+szasr722wCUr8\nIE521sAQvVrlagmnwDN6P0u5l7pVbBj+EQzXMu7P7qP9moZjnliGNeoRBxtiLcG2\nij2rd4VTyfYjrLEilKCpYYqBEoRI9wbHYgEtNLUNT9idwyGXKmRItTJPTKc+QbCv\nYijhqY5yZHFlrcX/9b/Broo7tHTOR5sN1tWu5Vk/BcU8Ya3LL8XM0NsOVBpktuCb\nRuvkW4KdE2sHiJy5ghCHeWQkG9aW1uSRwDg8Jk5GUQ", 
    client_email = "firebase-adminsdk-idxya@crm-hygge.iam.gserviceaccount.com", 
    client_id = "101533254845328435375", 
    auth_uri = "https://accounts.google.com/o/oauth2/auth", 
    token_uri = "https://oauth2.googleapis.com/token", 
    auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs", 
    client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-idxya%40crm-hygge.iam.gserviceaccount.com" 
}
